spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Iv1.cf77ae41f1138f74
            client-secret: d18402ef17ae4c720e126d34a5a09d5e499066ee

  data:
    cassandra:
      keyspace-name: main
      username: YWZsQpFnZpTwNKMYcptWzzOH
      password: 1T9kqFO4S+pQJm9uE7wMLA60TvHkQtZcwzO7n-Q87I,ykeIAzUudNGnYG76TUi1Rzfu_sNMdqobd29YFRtjYkbQkTMq97_YUo12dbB9Q2e3DtFiWU4SOxsTyu+D49Uhj
      schema-action: create_if_not_exists
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s

datastax.astra:
  secure-connect-bundle: secure-connect.zip


astra.db:
  id: 1abc91e1-0c01-4cf5-b3c6-6bdf826c2604
  region: us-east1
  keyspace: main
  application.token: AstraCS:YWZsQpFnZpTwNKMYcptWzzOH:4df300d9f940c2c84c81db3991210c3e3ef3801dd96cb73a4bfd5c3c4194dad9


spring.main.allow-circular-references: true

